### ISSUE TITLE
Cannot read properties of undefined (reading 'terminate')

### ISSUE THREAD

**Issue by YOUR1** [noppa/xmllint-wasm#19]
Whenever I try the browser-version with a simple class:

```typescript
import * as xmllint from "xmllint-wasm/index-browser";

export class ModelValidator {
    constructor(private xml: string) {}

    private async getSchema(): Promise<string> {
        const response = await fetch(Model.xsd');
        return await response.text()
    }

    async process(callback: any) {
        xmllint.memoryPages
        const { valid, rawOutput, normalized } = await xmllint.validateXML({
            xml: { fileName: 'model.xml', contents: this.xml },
            schema: await this.getSchema(),
            normalization: 'format'
        });
        callback(valid, rawOutput, normalized);
    }

}
```
I get the following error:
```
ModelValidator.ts:9 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'terminate')
TypeError: Cannot read properties of undefined (reading 'terminate')
    at index-browser.mjs:165:26
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:27450:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:27127:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:27127:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:25:1)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:27450:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
```

Is there something I need to do additionally?

**Comment by noppa** [comment]
What kind of bundler/build setup are you using? The stack trace implies that there may be some stuff going on that isn't coming from this lib, but probably zone.js. Sooo... Angular? What does your `ng version` (or `npx ng version` or something) say?

**Comment by noppa** [comment]
The only way that I can think of that this could happen is that if this line [in index.js](https://github.com/noppa/xmllint-wasm/blob/master/src/index.js#L162C20-L163C94) throws

```javascript
worker = new Worker(new URL('./xmllint-browser.mjs', import.meta.url), { type: 'module' });
```
Then `worker` will be undefined, and I guess I have a bit of an error handling bug in there that we kinda swallow the original error when we fail to terminate the never-created worker in `finally`.

Until the error handling problem is fixed, I recommend you open the index-browser.mjs file under node_modules, and try removing this line
```javascript
.finally(() => worker.terminate());
```
That won't fix the actual issue, but it will fix the poor error message and might give us better hint on why the worker can't be initialized.

**Comment by YOUR1** [comment]
> What kind of bundler/build setup are you using? The stack trace implies that there may be some stuff going on that isn't coming from this lib, but probably zone.js. Sooo... Angular? What does your `ng version` (or `npx ng version` or something) say?

Yeah, indeed. I'm using Angular (16.2.1);

**Comment by noppa** [comment]
I have fixed the confusing `Cannot read properties of undefined` error on version 4.0.2. This won't fix your actual issue, because for some reason or another the code running in your environment is not able to do `new Worker(...)`. But at least now it's easier to find the original error and focus on solving the actual issue, rather than an unrelated error that is more of an effect rather than the cause.

**Comment by noppa** [comment]
I'll close this issue now. Feel free to create a new one if this comes up again in version 5, preferably with an example XML and schema.
