### ISSUE TITLE
Promise cannot be cloned

### ISSUE THREAD

**Issue by paulhiggs** [noppa/xmllint-wasm#9]
I am getting the following error..
````
node:internal/per_context/domexception:53
    ErrorCaptureStackTrace(this);
    ^
DOMException [DataCloneError]: #<Promise> could not be cloned.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at new Worker (node:internal/worker:236:17)
    at validateXMLPromiseCb (E:\dvb-apps\dvb-i-tools\node_modules\xmllint-wasm\index.js:104:18)
    at new Promise (<anonymous>)
    at validateXML (E:\dvb-apps\dvb-i-tools\node_modules\xmllint-wasm\index.js:102:9)
    at newSchemaCheck2 (file:///E:/dvb-apps/dvb-i-tools/schema_checks.js:171:19)

Node.js v18.8.0
````
where the call to validateXML() is `const validationResult = await validateXML({ xml: XMLdoc, schema: schemas});`
and `XMLdoc` is the XML document and `schemas` is an array of four XML schemas.

I have checked the XMLdoc in Altova XMLspy against the four XML schemas and it all works OK

**Comment by noppa** [comment]
:thinking: I wonder if this is a Node 16 vs 18 thing. I've been using this with 16. Will try to repro with 18. If possible, could you try with 16?

**Comment by paulhiggs** [comment]
Just tried with node 16... same error
````
node:internal/per_context/domexception:53
    ErrorCaptureStackTrace(this);
    ^
DOMException [DataCloneError]: #<Promise> could not be cloned.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at new Worker (node:internal/worker:239:17)
    at validateXMLPromiseCb (E:\dvb-apps\dvb-i-tools\node_modules\xmllint-wasm\index.js:104:18)
    at new Promise (<anonymous>)
    at validateXML (E:\dvb-apps\dvb-i-tools\node_modules\xmllint-wasm\index.js:102:9)
    at newSchemaCheck2 (file:///E:/dvb-apps/dvb-i-tools/schema_checks.js:173:33)
    at ServiceListCheck.doSchemaVerification (file:///E:/dvb-apps/dvb-i-tools/sl-check.js:1454:4)
    at ServiceListCheck.doValidateServiceList (file:///E:/dvb-apps/dvb-i-tools/sl-check.js:1503:13)
    at DVB_I_check (file:///E:/dvb-apps/dvb-i-tools/Validator.js:160:27)
    at file:///E:/dvb-apps/dvb-i-tools/Validator.js:331:4

E:\dvb-apps\dvb-i-tools>node --version
v16.18.1
````

My code is this...
````
import {validateXML} from 'xmllint-wasm';

export async function newSchemaCheck2(XML, schemas, errs, errCode) 
{
	const XMLdoc = XML.toString();
	const validationResult = await validateXML({ xml: XMLdoc, schema: schemas});

	if (validationResult.valid) {
		console.log('There were no errors!');
	} else {
		console.warn(validationResult.errors);
	}
}
````

I could separately send you the XML document and schemas..

**Comment by noppa** [comment]
> I could separately send you the XML document and schemas

Thanks, that could help to repro the issue. My email address is in my profile.

**Comment by paulhiggs** [comment]
This seems to be related to Promises not being resolved before validateXML is called.
From a code perspective, this has been resolved and the validation proceeds using all schemas as expected.
